### ISSUE TITLE
README documentation for users

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/mixer#12]
Should we separate the Build and deploy sections into 2?

https://github.com/datacommonsorg/mixer#build-and-deploy

Build will probably only be used by core contributors, while deploy could be used by various admins.

Is there a system of tagging that we are going to follow? If so we should include that too.

**Comment by tjann** [comment]
Is build grouped with deploy because we need the build result to be in their private GCP project? We don't actually expect users to need more than one tag, since most will not be making changes to the build.

Suggestion: add comments to let users know they only need to build once, unless they git pull changes to the build.

Also--I'm assuming that when I'm making a private instance for Pew, I only need to run build&deploy. Are the rest applicable to me? It's not clear

**Comment by shifucun** [comment]
So the current README is for the development but here we like to have one for the private instance users which should be in "deployment" folder.

I will make that change.

**Comment by shifucun** [comment]
Fixed in https://github.com/datacommonsorg/mixer/pull/64
