### ISSUE TITLE
[FEEDBACK] Provide steps on environment setup

### ISSUE THREAD

**Issue by antaresc** [datacommonsorg/mixer#25]
Clients will have to have `go` setup locally, install the `gcloud` commandline interface, and have `protoc` installed.

It may be a good idea to provide some instructions on, or at least point to, how to perform these steps in addition to what currently exists in `README.md`.

**Comment by Spaceenter** [comment]
One idea is that the client just use docker to run locally. We have all the necessary steps in DOCKERFILE.

**Comment by ACscooter** [comment]
This is a pretty reasonable idea, we can provide instructions on how to run the docker image, then add additional comments in the docker file so that folks know how to the file.

**Comment by shifucun** [comment]
We have had a full fledged environment setup, both locally and in GKE with detailed steps now.
