### ISSUE TITLE
[BUG] Mixer responses are different depending on whether it hits BT or BQ

### ISSUE THREAD

**Issue by ACscooter** [datacommonsorg/mixer#27]
**Describe the bug**
When querying endpoints in the mixer, the response returns will use camel and snake case depending on if the response is from BigTable or BigQuery respectively.

**To Reproduce**
Call `GetTriples` with `dcid = geoId/06, limit=500` to force a query from BQ, unset limit to use BT.

**Expected behavior**
The response should be uniform independent of whether or not it is provided by BT or BQ.

**Screenshots**
A triple when the response is constructed from a BQ query. 
![image](https://user-images.githubusercontent.com/4650701/62995491-b0202c80-be15-11e9-94ba-60b6e95539f9.png)

A triple when the response is constructed from a BT query.
![image](https://user-images.githubusercontent.com/4650701/62995517-cb8b3780-be15-11e9-965d-6c72ca38e4a3.png)

**Comment by shifucun** [comment]
Fixed in a94fcee9b23fabeecf532c3c30d2bd6efb4038d6
