### ISSUE TITLE
[BUG] Validate Mixer rollout to ensure it is set up to best minimize downtime to traffic

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/mixer#342]

**Comment by pradh** [comment]
Bo points out that we use this strategy: https://source.cloud.google.com/datcom-ci/deployment/+/master:mixer/production/deployment.yaml;l=26-29

**Comment by shifucun** [comment]
Mixer rollout now uses readiness and liveness check and rollout strategy with 25% update rate: https://github.com/datacommonsorg/mixer/blob/master/deploy/base/deployment.yaml#L92-L100
