### ISSUE TITLE
[Feature Request] /stat/collection API latest date

### ISSUE THREAD

**Issue by intrepiditee** [datacommonsorg/mixer#369]
This is a feature request to make the `/stat/collection` API able to return the latest date (perhaps by default if `date` is not specified) and to include the dates in the response.

**Comment by shifucun** [comment]
@pradh Is it possible we produce the date information in the flume job as a separate cache?

**Comment by shifucun** [comment]
> Yeah, doable. So, would the cache key have everything as obs collection but the date?

Yeah, that would work. Thanks!

**Comment by shifucun** [comment]
@pradh Can you hold for the new cache. We wonder if it's better to have the cache without date in the key, ie, the cache will have ALL data for all the dates.

This way, mixer can respond with mixed date data of different places.

**Comment by pradh** [comment]
Do we really need ALL data? For example, US states have population data from 1920. Or, do we restrict time-series to up to N latest data points?

**Comment by shifucun** [comment]
This is solved in https://github.com/datacommonsorg/mixer/pull/512 by using the ObsSeries cache, scan through each sources and fetch the latest stat
