### ISSUE TITLE
[FEEDBACK] Update limit option in /node/triple to apply per predicate 

### ISSUE THREAD

**Issue by beets** [datacommonsorg/mixer#40]
Always return a complete list of predicates per dcid, but apply limits to each list.
The list of results should be stable -- i.e. limit=200 should return the results of limit=100 + 100 more.
If necessary, return an error if limit requested is too high.

**Comment by shifucun** [comment]
Now /node/triple limit is per predicate and neighbor type.

The maximum limit is 500
