### ISSUE TITLE
[BUG] Do not create a subscription every time

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/mixer#528]
https://github.com/datacommonsorg/mixer/blob/be325fa65b5aeddf74368b293e68a58a8185e7e1/internal/server/server.go#L163-L171

The code above creates a subscription every time. This then causes a bunch of one-off subscriptions (as below). Instead we should probably create a fixed subscription ID and use that ([doc](https://cloud.google.com/pubsub/docs/pull#synchronous_pull))

![image](https://user-images.githubusercontent.com/4375037/119078707-9416cb00-b9ab-11eb-8c4f-cbf0d033c74a.png)

**Comment by shifucun** [comment]
Each subscriber (with a unique ID) can only receives a topic once, is it possible to let all N subscriber with the same ID receive the topic? @pradh

**Comment by pradh** [comment]
I think you mean: can N subscriber tasks using the same subscription receive the same message on a given topic. Right? 

That's not possible, and I see the problem, we essentially want a broadcast message, but that is not possible with the Pub/Sub model.

An alternative is to have fixed per-pod subscribers "mixer-subscriber-pod-<ID>", but this is probably not too bad given the constraints.

**Comment by pradh** [comment]
There are ~567 of them.  Just wanted to confirm they do get deleted eventually?  In the fixed subscriber approach, we'll only have as many subscribers as pods.

![image](https://user-images.githubusercontent.com/4375037/119164800-a1ff3700-ba11-11eb-88cd-763a93191665.png)

**Comment by shifucun** [comment]
The number of pods in website/mixer (prod/staging/autopush/dev) are: [60, 24, 12, 6] and [54, 24, 8]. So during non-deploy time, there could be  ~180 subscribers. A subscriber will expires after 36h of inactivity ([config](https://github.com/datacommonsorg/mixer/blob/master/internal/server/server.go#L161)).

Note the actual subscribers could be larger than 180 after staging/prod push (almost double it), with cases that pod could restart a few times.

Maybe we can try [this](https://stackoverflow.com/questions/49621189/how-to-listen-for-graceful-server-termination-in-grpc) to [delete](https://pkg.go.dev/cloud.google.com/go/pubsub#Subscription.Delete) the subscription on pod shutdown, so the number could stay around ~180

**Comment by shifucun** [comment]
The subscribers are now deleted when server is shut down: https://github.com/datacommonsorg/mixer/blob/master/cmd/main.go#L156-L164
