### ISSUE TITLE
[FEEDBACK] Format of get_place_obs

### ISSUE THREAD

**Issue by ACscooter** [datacommonsorg/mixer#58]
For a combination of population type and constraining property values given to `get_place_obs`, there is only one population returned. Additionally, all observations returned have observedNode of the matching population.

In this case, it may be more reasonable to have the structure of the return value look like:

```
{
  "places": [
    {
      "name": <the name of the place>,
      "place": <the dcid>,
      "population": <the population id>, // instead of making it a dictionary
      "observations": [
        <All the observations>,
      ]
    },
    // And more...
  ]
}
```

The current structure with the dictionary of population -> observations suggests that for a combination of pop type and constraining pvs there could be multiple populations.

**Comment by Spaceenter** [comment]
Made the change to remove the layer of population from the result. Thanks for the suggestion.
