### ISSUE TITLE
[FEEDBACK] Return the same response for empty dcid list as partial dcid list

### ISSUE THREAD

**Issue by beets** [datacommonsorg/mixer#62]
I'm running into this issue from the Python API, and think we should handle it at the mixer level. Let me know if you think we should push this down the stack.

Issue: I'm trying to generate observation counts for all census race enums across counties. Some counties just don't have any data for certain enums, and others have partial coverage.

Instead of requiring the user to check if the dcid list of get_populations is made up of empty strings, should the mixer return an empty payload?

The current error message was hard to understand as well:

> {
>   "dcids": [
>     ""
>   ],
>   "measuredProperty": "count",
>   "observationDate": "2017",
>   "measurementMethod": "CenusACS5yrSurvey",
>   "statsType": "measuredValue"
> }
> ==>   "googleapi: Error 400: Syntax error: Expected keyword FALSE or keyword NULL or keyword TRUE but got identifier \"NULLAND\" at [1:206], invalidQuery"

vs

> {
>   "dcids": [
>     "dc/p/9br9jdcn2qpbd",
>     ""
>   ],
>   "measuredProperty": "count",
>   "observationDate": "2017",
>   "measurementMethod": "CenusACS5yrSurvey",
>   "statsType": "measuredValue"
> }
> 
> {
>   "payload": "[{\"dcid\":\"dc/p/9br9jdcn2qpbd\",\"observation\":\"175.000000\"}]"
> }

**Comment by shifucun** [comment]
Can you share a query url for this particular query?

**Comment by beets** [comment]
Partial dcid list:
https://endpointsportal.datcom-mixer.cloud.goog/docs/api.datacommons.org/g/routes/node/observations/post?apix_params=%7B"__request_body__"%3A%7B"dcids"%3A%5B"dc%2Fp%2F9br9jdcn2qpbd"%2C""%5D%2C"measuredProperty"%3A"count"%2C"observationDate"%3A"2017"%2C"measurementMethod"%3A"CenusACS5yrSurvey"%2C"statsType"%3A"measuredValue"%7D%7D

Empty dcid list:
https://endpointsportal.datcom-mixer.cloud.goog/docs/api.datacommons.org/g/routes/node/observations/post?apix_params=%7B"__request_body__"%3A%7B"dcids"%3A%5B""%5D%2C"measuredProperty"%3A"count"%2C"observationDate"%3A"2017"%2C"measurementMethod"%3A"CenusACS5yrSurvey"%2C"statsType"%3A"measuredValue"%7D%7D

**Comment by shifucun** [comment]
Fixed in https://github.com/datacommonsorg/mixer/pull/63
